apiVersion: v1
kind: Service
metadata:
  name: python-svc
  namespace: xray-api
  labels:
    app: python-api
spec:
  type: ClusterIP
  selector:
    app: python-api
  ports:
    - name: http
      port: 8001
      targetPort: 8001