apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
  namespace: xray-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
    spec:
      containers:
        - name: python-api
          image: py-api:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          envFrom:
            - configMapRef: { name: db-config }
            - secretRef:    { name: db-secrets }
          readinessProbe:
            httpGet:
              path: /api/readyz
              port: 8001
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/livez
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 10
