apiVersion: v1
kind: ServiceAccount
metadata:
  name: xray-operator
  namespace: xray-api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: xray-operator-role
  namespace: xray-api
rules:
- apiGroups: ["", "apps", "autoscaling"]
  resources: ["pods","services","deployments","replicasets","events","horizontalpodautoscalers"]
  verbs: ["get","list","watch","create","update","patch","delete"]
- apiGroups: ["medai.mcolak.io"]
  resources: ["xrayapps","xrayapps/status"]
  verbs: ["get","list","watch","create","update","patch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: xray-operator-rb
  namespace: xray-api
subjects:
- kind: ServiceAccount
  name: xray-operator
  namespace: xray-api
roleRef:
  kind: Role
  name: xray-operator-role
  apiGroup: rbac.authorization.k8s.io