apiVersion: apps/v1
kind: Deployment
metadata:
  name: xray-operator
  namespace: xray-api
spec:
  replicas: 1
  selector: { matchLabels: { app: xray-operator } }
  template:
    metadata:
      labels: { app: xray-operator }
    spec:
      serviceAccountName: xray-operator
      securityContext:                
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: operator
          image: xray-operator:0.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: KOPF_LOGLEVEL
              value: INFO
          securityContext:            
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]