apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: allow-no-apparmor-in-xray
  namespace: xray-api
spec:
  exceptions:
    - policyName: require-apparmor
      ruleNames: ["autogen-apparmor-runtime-default"]
  match:
    any:
      - resources:
          kinds: ["Pod","Deployment","StatefulSet","Job","DaemonSet","ReplicaSet"]
          namespaces: ["xray-api"]