apiVersion: v1
kind: Service
metadata:
  name: db-svc
  namespace: xray-api
  labels:
    app: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: pg
      port: 5432
      targetPort: 5432