apiVersion: v1
kind: Service
metadata:
  name: db-svc-hl
  namespace: xray-api
  labels: { app: postgres }
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - name: pg
      port: 5432
      targetPort: 5432