apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-sql
  namespace: xray-api
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS logs_user (
      id BIGSERIAL PRIMARY KEY,
      ip TEXT NOT NULL,
      payload JSONB NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
    CREATE TABLE IF NOT EXISTS logs_error (
      id BIGSERIAL PRIMARY KEY,
      ip TEXT NOT NULL,
      payload JSONB NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
    CREATE TABLE IF NOT EXISTS logs_access (
      id BIGSERIAL PRIMARY KEY,
      ip TEXT NOT NULL,
      payload JSONB NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );