# Pod level
apiVersion: v1
kind: ResourceQuota
metadata:
  name: python-api-rq
  namespace: xray-api
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 4Gi
    limits.cpu: "6"
    limits.memory: 8Gi
    pods: "30"
--- # Container level
apiVersion: v1
kind: LimitRange
metadata:
  name: python-api-lr
  namespace: xray-api
spec:
  limits:
    - type: Container
      default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "200m"
        memory: "256Mi"