apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
  namespace: xray-api
data:
  INTERNAL_BASE_URL: "http://python-api:8001"
---
apiVersion: v1
kind: Secret
metadata:
  name: gateway-secrets
  namespace: xray-api
type: Opaque
stringData:
  DB_DSN: "postgres://xray_user:12345@postgres:5432/xray"