apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-pod-security-restricted
spec:
  validationFailureAction: enforce
  rules:
  - name: require-seccomp
    match: { resources: { kinds: ["Pod"], namespaces: ["xray-api"] } }
    validate:
      message: "Pods must use seccompProfile RuntimeDefault"
      pattern:
        spec:
          securityContext:
            seccompProfile:
              type: "RuntimeDefault"
  - name: require-container-security
    match: { resources: { kinds: ["Pod"], namespaces: ["xray-api"] } }
    validate:
      message: "Containers must run as non-root, readOnlyRootFilesystem, no privilege escalation, drop ALL caps"
      pattern:
        spec:
          containers:
          - =(name): "*"
            securityContext:
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["ALL"]