apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-tag
spec:
  validationFailureAction: enforce
  rules:
  - name: no-latest
    match: { resources: { kinds: ["Pod"], namespaces: ["xray-api"] } }
    validate:
      message: "Do not use :latest tags."
      pattern:
        spec:
          containers:
          - image: "!*:latest"