apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-resources-and-probes
spec:
  validationFailureAction: enforce
  rules:
  - name: resource-limits
    match: { resources: { kinds: ["Pod"], namespaces: ["xray-api"] } }
    validate:
      message: "All containers must define CPU/Memory requests & limits."
      pattern:
        spec:
          containers:
          - resources:
              requests:
                memory: "?*"
                cpu: "?*"
              limits:
                memory: "?*"
                cpu: "?*"
  - name: health-probes
    match: { resources: { kinds: ["Pod"], namespaces: ["xray-api"] } }
    validate:
      message: "All containers must have readiness & liveness probes."
      pattern:
        spec:
          containers:
          - readinessProbe: { ?*: "?*" }
            livenessProbe:  { ?*: "?*" }